### ISSUE TITLE
Inproper block perk tree.

### ISSUE THREAD

**Issue by reminafag** [chrizel/skyrim#3]
Both paths in the block tree should lead to Shield Charge perk, but instead only the right one do. 
![capture](https://user-images.githubusercontent.com/19939204/29896500-e2f39cd0-8de5-11e7-85d7-af768a0a4c81.PNG)

**Comment by aaronmaynard** [comment]
As this seemed inactive I have updated and fixed the issue with the block tree.
https://aaronmaynard.github.io/Skyrim-Perk-Utility/

**Comment by chrizel** [comment]
Problem fixed thanks to @aaronmaynard
